In [1]:
# instalar postgres
!apt update -qq
!apt install postgresql postgresql-contrib -y -qq
!service postgresql start

#archivos csv
!wget -q -O /content/games.csv          "https://drive.google.com/uc?export=download&id=1POGckTr-0yEU-SR7X4r6nQA8tUKg9zMz"
!wget -q -O /content/characters.csv     "https://drive.google.com/uc?export=download&id=1KP8NE9TbE78MhY7WnD1GefBsDH_77QAb"
!wget -q -O /content/scenes.csv         "https://drive.google.com/uc?export=download&id=1kufbWlvNXCSU4lPoGT4i6oTl16sSAjFs"
!wget -q -O /content/interactions.csv   "https://drive.google.com/uc?export=download&id=1P9-Og73bIGqsOaYQhCqg5D3muNQeeG2q"
!wget -q -O /content/gameAppearance.csv "https://drive.google.com/uc?export=download&id=1Voj4H89bbwhVjv4nrhuq27rkpgY8QViY"

# crear usuario y base de datos
!sudo -u postgres psql -c "CREATE USER root WITH SUPERUSER PASSWORD 'root';"
!sudo -u postgres createdb guia -O root

# extension SQL
%load_ext sql
%config SqlMagic.feedback=False
%config SqlMagic.autopandas=True
%config SqlMagic.style = '_DEPRECATED_DEFAULT'

# conexion
%sql postgresql+psycopg2://root:root@localhost/guia

22 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
postgresql is already the newest version (14+238).
postgresql-contrib is already the newest version (14+238).
0 upgraded, 0 newly installed, 0 to remove and 22 not upgraded.
 * Starting PostgreSQL 14 database server
   ...done.
ERROR:  role "root" already exists
createdb: error: database creation failed: ERROR:  database "guia" already exists

## 1) Crear Tablas:

Esquema:

*   games(game_id PK, title, year, type, chronology_order)
*   characters(character_id PK, name, role)
*   scenes(scene_id PK, game_id FK → games(game_id), title, source)
*   interactions(game_id FK → games(game_id), scene_id FK → scenes(scene_id), character_id FK → characters(character_id))
*   game_appearance(game_id FK → games(game_id), character_id FK → characters(character_id), role, game_title, character_name, PK (game_id, character_id))

### Tabla games (solución)

In [2]:
%%sql
DROP TABLE IF EXISTS game_appearance CASCADE;
DROP TABLE IF EXISTS interactions CASCADE;
DROP TABLE IF EXISTS scenes CASCADE;
DROP TABLE IF EXISTS characters CASCADE;
DROP TABLE IF EXISTS games CASCADE;

CREATE TABLE games (
    game_id          VARCHAR(10) PRIMARY KEY,
    title            VARCHAR(50) NOT NULL,
    year             INTEGER,
    type             VARCHAR(10),
    chronology_order INTEGER
);

 * postgresql+psycopg2://root:***@localhost/guia

Empty DataFrame
Columns: []
Index: []

### Tabla characters (solución)

In [3]:
%%sql
CREATE TABLE characters (
    character_id INTEGER PRIMARY KEY,
    name         VARCHAR(50) NOT NULL,
    role         VARCHAR(10)
);

 * postgresql+psycopg2://root:***@localhost/guia

Empty DataFrame
Columns: []
Index: []

### Tabla scenes (solución)

In [4]:
%%sql
CREATE TABLE scenes (
    scene_id VARCHAR(15) PRIMARY KEY,
    game_id  VARCHAR(10) REFERENCES games(game_id),
    title    VARCHAR(700),
    source   VARCHAR(100)
);

 * postgresql+psycopg2://root:***@localhost/guia

Empty DataFrame
Columns: []
Index: []

### Tabla interactions (solución)

In [5]:
%%sql
CREATE TABLE interactions (
    game_id      VARCHAR(10) REFERENCES games(game_id),
    scene_id     VARCHAR(15) REFERENCES scenes(scene_id),
    character_id INTEGER     REFERENCES characters(character_id),
    PRIMARY KEY (game_id, scene_id, character_id)
);

 * postgresql+psycopg2://root:***@localhost/guia

Empty DataFrame
Columns: []
Index: []

### Tabla game_appearance (solución)

In [6]:
%%sql
CREATE TABLE game_appearance (
    game_id        VARCHAR(10) REFERENCES games(game_id),
    character_id   INTEGER     REFERENCES characters(character_id),
    role           VARCHAR(10),
    game_title     VARCHAR(50),
    character_name VARCHAR(50),
    PRIMARY KEY (game_id, character_id)
);

 * postgresql+psycopg2://root:***@localhost/guia

Empty DataFrame
Columns: []
Index: []

In [7]:
# 2. Ejecuta el código para poblar las tablas creadas
%%sql
COPY games(game_id, title, year, type, chronology_order)
FROM '/content/games.csv'
DELIMITER ','
CSV HEADER;

COPY characters(character_id, name, role)
FROM '/content/characters.csv'
DELIMITER ','
CSV HEADER;

COPY scenes(game_id, scene_id, title, source)
FROM '/content/scenes.csv'
DELIMITER ','
CSV HEADER;

COPY interactions(game_id, scene_id, character_id)
FROM '/content/interactions.csv'
DELIMITER ','
CSV HEADER;

COPY game_appearance(game_id, character_id, role, game_title, character_name)
FROM '/content/gameAppearance.csv'
DELIMITER ','
CSV HEADER;

 * postgresql+psycopg2://root:***@localhost/guia

Empty DataFrame
Columns: []
Index: []

In [8]:
%%sql
SELECT * FROM games;

 * postgresql+psycopg2://root:***@localhost/guia

,game_id,title,year,type,chronology_order
0,re,Resident Evil,1996,mainline,2
1,re2,Resident Evil 2,1998,mainline,4
2,re3,Resident Evil 3: Nemesis,1999,mainline,3
3,re_ve,Resident Evil: Code – Veronica,2000,mainline,5
4,re0,Resident Evil 0,2002,mainline,1
5,re4,Resident Evil 4,2005,mainline,6
6,re5,Resident Evil 5,2009,mainline,8
7,re_re,Resident Evil: Revelations,2012,spinoff,7
8,re6,Resident Evil 6,2012,mainline,10
9,re_re2,Resident Evil: Revelations 2,2015,spinoff,9
10,re7,Resident Evil 7: Biohazard,2017,mainline,11
11,re8,Resident Evil Village,2021,mainline,12
12,re_sr,Resident Evil Village – Shadow of Rose,2022,spinoff,13
13,re9,Resident Evil Requiem,2026,mainline,14

In [9]:
%%sql
SELECT * FROM characters;

 * postgresql+psycopg2://root:***@localhost/guia

    character_id                name     role
0              1  Leon Scott Kennedy     hero
1              2       Ashley Graham     hero
2              3            Ada Wong     hero
3              4     Ingrid Hunnigan     hero
4              5           Luis Sera     hero
..           ...                 ...      ...
78            79    Donna Beneviento  villain
79            80      Grace Ashcroft     hero
80            81       Victor Gideon  villain
81            82      Nathan Dempsey  support
82            83     Alyssa Ashcroft  support

[83 rows x 3 columns]

In [21]:
%%sql
SELECT * FROM scenes
LIMIT 20;

 * postgresql+psycopg2://root:***@localhost/guia

,scene_id,game_id,title,source
0,re_01,re,Opening FMV,https://gamefaqs.gamespot.com/ps/198462-reside...
1,re_02,re,Inside The Mansion,https://gamefaqs.gamespot.com/ps/198462-reside...
2,re_03,re,The Dining Room,https://gamefaqs.gamespot.com/ps/198462-reside...
3,re_04,re,Mysterious Puddle,https://gamefaqs.gamespot.com/ps/198462-reside...
4,re_05,re,Researcher's Will Event (Note: This scene will...,https://gamefaqs.gamespot.com/ps/198462-reside...
5,re_06,re,Draining the Pool CGI,https://gamefaqs.gamespot.com/ps/198462-reside...
6,re_07,re,Muffled Conversation (Note: You must have hear...,https://gamefaqs.gamespot.com/ps/198462-reside...
7,re_08,re,Reunite With Wesker,https://gamefaqs.gamespot.com/ps/198462-reside...
8,re_09,re,Hunter CGI,https://gamefaqs.gamespot.com/ps/198462-reside...
9,re_10,re,Snake Confrontation,https://gamefaqs.gamespot.com/ps/198462-reside...
10,re_11,re,Zombie CGI #2,https://gamefaqs.gamespot.com/ps/198462-reside...
11,re_12,re,Trust Barry?,https://gamefaqs.gamespot.com/ps/198462-reside...
12,re_13,re,Draining the Fountain CGI,https://gamefaqs.gamespot.com/ps/198462-reside...
13,re_14,re,Slideshow,https://gamefaqs.gamespot.com/ps/198462-reside...
14,re_15,re,Tyrant CGI,https://gamefaqs.gamespot.com/ps/198462-reside...
15,re_16,re,Radio Transmission #3,https://gamefaqs.gamespot.com/ps/198462-reside...
16,re_17,re,"Jill Epilogue Picture (Note: To see this, you ...",https://gamefaqs.gamespot.com/ps/198462-reside...
17,re_18,re,Opening FMV,https://gamefaqs.gamespot.com/ps/198462-reside...
18,re_19,re,Inside the Mansion,https://gamefaqs.gamespot.com/ps/198462-reside...
19,re_20,re,Zombie CGI,https://gamefaqs.gamespot.com/ps/198462-reside...

In [11]:
%%sql
SELECT * FROM interactions;

 * postgresql+psycopg2://root:***@localhost/guia

     game_id scene_id  character_id
0         re    re_01            16
1         re    re_01             6
2         re    re_01            15
3         re    re_02            16
4         re    re_02            17
...      ...      ...           ...
1532     re9  re9_643            80
1533     re9  re9_644            80
1534     re9  re9_644             1
1535     re9  re9_645            80
1536     re9  re9_646            80

[1537 rows x 3 columns]

In [12]:
%%sql
SELECT * FROM game_appearance;

 * postgresql+psycopg2://root:***@localhost/guia

,game_id,character_id,role,game_title,character_name
0,re,6,villain,Resident Evil,Albert Wesker
1,re,15,hero,Resident Evil,Chris Redfield
2,re,16,hero,Resident Evil,Jill Valentine
3,re,17,support,Resident Evil,Barry Burton
4,re,18,support,Resident Evil,Brad Vickers
...,...,...,...,...,...
110,re_ve,25,hero,Resident Evil: Code – Veronica,Claire Redfield
111,re_ve,38,hero,Resident Evil: Code – Veronica,Steve Burnside
112,re_ve,39,villain,Resident Evil: Code – Veronica,Alexia Ashford
113,re_ve,40,villain,Resident Evil: Code – Veronica,Alfred Ashford
114,re_ve,41,support,Resident Evil: Code – Veronica,Rodrigo Juan Raval

## 3. Consultas SQL

### Consulta 0: En que juegos aparece Leon S Kennedy

In [13]:
%%sql
SELECT g.title, ga.role
FROM game_appearance ga
JOIN games g ON ga.game_id = g.game_id
JOIN characters c ON ga.character_id = c.character_id
WHERE c.name = 'Leon Scott Kennedy'
ORDER BY g.chronology_order;

 * postgresql+psycopg2://root:***@localhost/guia

                   title  role
0        Resident Evil 2  hero
1        Resident Evil 4  hero
2        Resident Evil 6  hero
3  Resident Evil Requiem  hero

### Consulta 1: TOP 10 personajes con más apariciones en juegos

In [14]:
%%sql
SELECT
    c.name,
    c.role,
    COUNT(ga.game_id) AS total_apariciones
FROM characters c
JOIN game_appearance ga ON c.character_id = ga.character_id
GROUP BY c.character_id, c.name, c.role
ORDER BY total_apariciones DESC
LIMIT 10;

 * postgresql+psycopg2://root:***@localhost/guia

                 name     role  total_apariciones
0      Chris Redfield     hero                  6
1       Albert Wesker  villain                  5
2      Jill Valentine     hero                  4
3  Leon Scott Kennedy     hero                  4
4     Claire Redfield     hero                  3
5       Sherry Birkin  support                  3
6            Ada Wong     hero                  3
7       Ethan Winters     hero                  3
8    Rosemary Winters  support                  2
9        Barry Burton     hero                  2

### Consulta 2: Juegos con más escenas

In [36]:
%%sql
SELECT
    g.title,
    g.year,
    COUNT(s.scene_id) AS total_escenas
FROM games g
JOIN scenes s ON g.game_id = s.game_id
GROUP BY g.game_id, g.title, g.year
ORDER BY total_escenas DESC;

 * postgresql+psycopg2://root:***@localhost/guia

                                     title  year  total_escenas
0                    Resident Evil Requiem  2026            646
1   Resident Evil Village – Shadow of Rose  2022            248
2               Resident Evil 7: Biohazard  2017            227
3                 Resident Evil 3: Nemesis  1999            180
4                          Resident Evil 2  1998             80
5                          Resident Evil 5  2009             48
6                          Resident Evil 0  2002             36
7                            Resident Evil  1996             36
8           Resident Evil: Code – Veronica  2000             34
9                          Resident Evil 4  2005             18
10                         Resident Evil 6  2012             10
11                   Resident Evil Village  2021             10

### Consulta 3: Protagonistas (hero) que aparecen en MÁS de un juego

In [35]:
%%sql
SELECT
    c.name,
    COUNT(ga.game_id) AS juegos
FROM characters c
JOIN game_appearance ga ON c.character_id = ga.character_id
WHERE ga.role = 'hero'
GROUP BY c.character_id, c.name
HAVING COUNT(ga.game_id) > 1
ORDER BY juegos DESC;

 * postgresql+psycopg2://root:***@localhost/guia

                 name  juegos
0      Chris Redfield       5
1  Leon Scott Kennedy       4
2     Claire Redfield       3
3      Jill Valentine       3
4       Ethan Winters       2

### Consulta 4: Distribución de tipos de juego por década

In [34]:
%%sql
SELECT
    (year / 10) * 10 AS decada,
    type,
    COUNT(*) AS cantidad
FROM games
GROUP BY decada, type
ORDER BY decada, type;

 * postgresql+psycopg2://root:***@localhost/guia

   decada      type  cantidad
0    1990  mainline         3
1    2000  mainline         4
2    2010  mainline         2
3    2010   spinoff         2
4    2020  mainline         2
5    2020   spinoff         1

### Consulta 5:  TOP 10 escenas con más personajes involucrados

In [33]:
%%sql
SELECT
    s.scene_id,
    s.title AS escena,
    g.title AS juego,
    COUNT(DISTINCT i.character_id) AS personajes_involucrados
FROM scenes s
JOIN interactions i ON s.scene_id = i.scene_id
JOIN games g ON s.game_id = g.game_id
GROUP BY s.scene_id, s.title, g.title
ORDER BY personajes_involucrados DESC
LIMIT 10;

 * postgresql+psycopg2://root:***@localhost/guia

,scene_id,escena,juego,personajes_involucrados
0,re6_008,Chapter 3,Resident Evil 6,5
1,re5_042,A New Nightmare Begins,Resident Evil 5,5
2,re6_007,Chapter 2,Resident Evil 6,5
3,re6_010,Chapter 5,Resident Evil 6,5
4,re4_011,Chapter 4-1,Resident Evil 4,5
5,re6_004,Chapter 4,Resident Evil 6,5
6,re4_007,Chapter 3-1,Resident Evil 4,4
7,re_34,Radio Transmission #3,Resident Evil,4
8,re2_80,Its up to us to take out umbrella!,Resident Evil 2,4
9,re_31,Slideshow,Resident Evil,4

### Consulta 6: Para cada escena con más de un personaje, mostrar el juego, la escena y los nombres de los personajes involucrados

In [32]:
%%sql
SELECT
    g.title        AS juego,
    s.title        AS escena,
    c.name         AS personaje
FROM interactions i
JOIN games      g ON i.game_id      = g.game_id
JOIN scenes     s ON i.scene_id     = s.scene_id
JOIN characters c ON i.character_id = c.character_id
WHERE i.scene_id IN (
    SELECT scene_id
    FROM interactions
    GROUP BY scene_id
    HAVING COUNT(DISTINCT character_id) > 1
)
ORDER BY g.chronology_order, s.scene_id, c.name;

 * postgresql+psycopg2://root:***@localhost/guia

,juego,escena,personaje
0,Resident Evil 0,Prologue,Edward Dewey
1,Resident Evil 0,Prologue,Enrico Marini
2,Resident Evil 0,Prologue,Rebecca Chambers
3,Resident Evil 0,Meet Lt. Coen,Billy Coen
4,Resident Evil 0,Meet Lt. Coen,Rebecca Chambers
...,...,...,...
851,Resident Evil Requiem,Grace is distracted from the phone.,Nathan Dempsey
852,Resident Evil Requiem,The room begins to collapse.,Grace Ashcroft
853,Resident Evil Requiem,The room begins to collapse.,Leon Scott Kennedy
854,Resident Evil Requiem,"Zeno lands numerous blows on Leon, breaking ri...",Grace Ashcroft
855,Resident Evil Requiem,"Zeno lands numerous blows on Leon, breaking ri...",Leon Scott Kennedy